version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: hooks/beforeinstall.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: hooks/afterinstall.sh
      timeout: 300
      # runas: ec2-user
  ApplicationStart:
    - location: hooks/start_server.sh
      timeout: 300
      # runas: ec2-user
  ApplicationStop:
    - location: hooks/stop_server.sh
      timeout: 300
      # runas: ec2-user

#
  # permissions:
  # - object: /usr/bin/env
  #   owner: ec2-user
  #   group: ec2-user
  #   mode: 744
  #   type:
  #     - directory
  #     - file